### ISSUE TITLE
IndexError on BookMyshow

### ISSUE THREAD

**Issue by soubhiksb** [agarwalsarthak121/web_crawlers#1]
Raises 'IndexError' in your BookMyshow Script.

**Comment by soubhiksb** [comment]
Found out that the class 'timings' is served via JavaScript instead of the deafult HTML page. That's why it was throwing error as no content was there. I hope using JSON will fix it.

**Comment by agarwalsarthak121** [comment]
Thanks, i was also facing issues with that script.
