### ISSUE TITLE
File still named as tpd.py in README.md

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [agarwalsarthak121/web_crawlers#4]
As the file name was changed recently from tpd.py to tutorialsPointDownloader.py, there wasn't any modification to the readme file of the repo. This lead me to uselessly search for tpd.py instead among the files.

**Comment by agarwalsarthak121** [comment]
Sorry for the inconvenience caused to you.I have updated the Readme file. Thanks for mentioning.
