### ISSUE TITLE
Where does ”pynotify“ exist?

### ISSUE THREAD

**Issue by bodii** [agarwalsarthak121/web_crawlers#7]
I didn't find any suitable installation files for this library in your code on github and python.org. I tried to use pip to install it, but the installation is not a desktop prompt at all, there is no corresponding init method.

**Comment by agarwalsarthak121** [comment]
it is not a python library. It is a separate software u have to install on your linux machine to run the code.
Use **sudo apt-get install pynotify**.
Check if you are able to install.
